@startuml
skinparam classAttributeIconSize 0

class Venue {
  # capacity : integer
  # space : bolean
  # count : integer
  Venue()
  void person_entered()
  void person_left()
  get_count() : integer
  get_capacity() : integer
  get_stapce() : bolean
  void is_full()
  void not_full()
  void print_cur_visitors()
}
@enduml
